// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool.WebAPI.Data;

#nullable disable

namespace SmartSchool.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apelido")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apelido = "Kent",
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(787),
                            DataNascimento = new DateTime(2002, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 1,
                            Nome = "Marta",
                            Telefone = "33225555"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apelido = "Isabela",
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(800),
                            DataNascimento = new DateTime(2003, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 2,
                            Nome = "Paula",
                            Telefone = "3354288"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apelido = "Antonia",
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(808),
                            DataNascimento = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 3,
                            Nome = "Laura",
                            Telefone = "55668899"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Apelido = "Maria",
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(817),
                            DataNascimento = new DateTime(2001, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 4,
                            Nome = "Luiza",
                            Telefone = "6565659"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Apelido = "Machado",
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(822),
                            DataNascimento = new DateTime(1999, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 5,
                            Nome = "Lucas",
                            Telefone = "565685415"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Apelido = "Alvares",
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(831),
                            DataNascimento = new DateTime(2004, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 6,
                            Nome = "Pedro",
                            Telefone = "456454545"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Apelido = "José",
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(837),
                            DataNascimento = new DateTime(2006, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 7,
                            Nome = "Paulo",
                            Telefone = "9874512"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoCurso", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("datetime");

                    b.HasKey("AlunoId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("AlunosCursos");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            CursoId = 1,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(859)
                        },
                        new
                        {
                            AlunoId = 2,
                            CursoId = 2,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(864)
                        },
                        new
                        {
                            AlunoId = 3,
                            CursoId = 3,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(867)
                        },
                        new
                        {
                            AlunoId = 4,
                            CursoId = 2,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(869)
                        },
                        new
                        {
                            AlunoId = 5,
                            CursoId = 3,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(871)
                        },
                        new
                        {
                            AlunoId = 6,
                            CursoId = 2,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(875)
                        },
                        new
                        {
                            AlunoId = 7,
                            CursoId = 3,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(877)
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("datetime");

                    b.Property<int?>("Nota")
                        .HasColumnType("int");

                    b.HasKey("AlunoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 2,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(901)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 4,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(906)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 5,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(908)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 1,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(910)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 2,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(913)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 5,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(917)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 1,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(919)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 2,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(921)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 3,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(923)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 1,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(926)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 4,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(929)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 5,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(931)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 4,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(933)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 5,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(935)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 1,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(938)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 2,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(940)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 3,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(942)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 4,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(945)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 1,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(948)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 2,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(950)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 3,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(952)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 4,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(954)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 5,
                            DataMatricula = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(956)
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tecnologias de Informação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Sistemas de Informação"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ciência da Computação"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int?>("PreRequisitoId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("PreRequisitoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Física",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 4,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Português",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 5,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 6,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 7,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 8,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 9,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 10,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Programação",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apelido")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataFimContrato")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataInicioContrato")
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int>("Registo")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apelido = "António",
                            DataInicioContrato = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(556),
                            Nome = "Lauro",
                            Registo = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apelido = "Cavaliery",
                            DataInicioContrato = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(605),
                            Nome = "Roberto",
                            Registo = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apelido = "Junior",
                            DataInicioContrato = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(608),
                            Nome = "Ronaldo",
                            Registo = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Apelido = "Leão",
                            DataInicioContrato = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(611),
                            Nome = "Rodrigo",
                            Registo = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Apelido = "Dumas",
                            DataInicioContrato = new DateTime(2022, 11, 7, 15, 50, 41, 409, DateTimeKind.Local).AddTicks(613),
                            Nome = "Alexandre",
                            Registo = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoCurso", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Aluno", "Aluno")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Disciplina", "Disciplina")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Disciplina", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Curso", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Disciplina", "PreRequisito")
                        .WithMany()
                        .HasForeignKey("PreRequisitoId");

                    b.HasOne("SmartSchool.WebAPI.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("PreRequisito");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Aluno", b =>
                {
                    b.Navigation("AlunosDisciplinas");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Curso", b =>
                {
                    b.Navigation("Disciplinas");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Disciplina", b =>
                {
                    b.Navigation("AlunosDisciplinas");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Professor", b =>
                {
                    b.Navigation("Disciplinas");
                });
#pragma warning restore 612, 618
        }
    }
}
