// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool.WebAPI.Data;

#nullable disable

namespace SmartSchool.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apelido")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Matricula")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apelido = "Kent",
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2558),
                            DataNascimento = new DateTime(2002, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 1,
                            Nome = "Marta",
                            Telefone = "33225555"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apelido = "Isabela",
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2567),
                            DataNascimento = new DateTime(2003, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 2,
                            Nome = "Paula",
                            Telefone = "3354288"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apelido = "Antonia",
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2573),
                            DataNascimento = new DateTime(2000, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 3,
                            Nome = "Laura",
                            Telefone = "55668899"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Apelido = "Maria",
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2579),
                            DataNascimento = new DateTime(2001, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 4,
                            Nome = "Luiza",
                            Telefone = "6565659"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Apelido = "Machado",
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2584),
                            DataNascimento = new DateTime(1999, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 5,
                            Nome = "Lucas",
                            Telefone = "565685415"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Apelido = "Alvares",
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2692),
                            DataNascimento = new DateTime(2004, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 6,
                            Nome = "Pedro",
                            Telefone = "456454545"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Apelido = "José",
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2700),
                            DataNascimento = new DateTime(2006, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 7,
                            Nome = "Paulo",
                            Telefone = "9874512"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoCurso", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("AlunosCursos");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            CursoId = 1,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2726)
                        },
                        new
                        {
                            AlunoId = 2,
                            CursoId = 2,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2731)
                        },
                        new
                        {
                            AlunoId = 3,
                            CursoId = 3,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2733)
                        },
                        new
                        {
                            AlunoId = 4,
                            CursoId = 2,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2734)
                        },
                        new
                        {
                            AlunoId = 5,
                            CursoId = 3,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2736)
                        },
                        new
                        {
                            AlunoId = 6,
                            CursoId = 2,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2739)
                        },
                        new
                        {
                            AlunoId = 7,
                            CursoId = 3,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2741)
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Nota")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 2,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2757)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 4,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2761)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 5,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2763)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 1,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2764)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 2,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2807)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 5,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2811)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 1,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2812)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 2,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2814)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 3,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2816)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 1,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2818)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 4,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2820)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 5,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2822)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 4,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2824)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 5,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2825)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 1,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2827)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 2,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2829)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 3,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2831)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 4,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2834)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 1,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2836)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 2,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2837)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 3,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2839)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 4,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2841)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 5,
                            DataMatricula = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2843)
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tecnologias de Informação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Sistemas de Informação"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ciência da Computação"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreRequisitoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("PreRequisitoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Física",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 4,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Português",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 5,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 6,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 7,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 8,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 9,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 10,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Programação",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apelido")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFimContrato")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicioContrato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Registo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apelido = "António",
                            DataInicioContrato = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2306),
                            Nome = "Lauro",
                            Registo = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apelido = "Cavaliery",
                            DataInicioContrato = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2342),
                            Nome = "Roberto",
                            Registo = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apelido = "Junior",
                            DataInicioContrato = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2344),
                            Nome = "Ronaldo",
                            Registo = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Apelido = "Leão",
                            DataInicioContrato = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2346),
                            Nome = "Rodrigo",
                            Registo = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Apelido = "Dumas",
                            DataInicioContrato = new DateTime(2022, 11, 4, 19, 1, 44, 403, DateTimeKind.Local).AddTicks(2348),
                            Nome = "Alexandre",
                            Registo = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoCurso", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Aluno", "Aluno")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Disciplina", "Disciplina")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Disciplina", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Curso", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Disciplina", "PreRequisito")
                        .WithMany()
                        .HasForeignKey("PreRequisitoId");

                    b.HasOne("SmartSchool.WebAPI.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("PreRequisito");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Aluno", b =>
                {
                    b.Navigation("AlunosDisciplinas");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Curso", b =>
                {
                    b.Navigation("Disciplinas");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Disciplina", b =>
                {
                    b.Navigation("AlunosDisciplinas");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Professor", b =>
                {
                    b.Navigation("Disciplinas");
                });
#pragma warning restore 612, 618
        }
    }
}
