version: "3.8"

volumes:
  smartschooldb:

networks:
  mysqlNET:
  smartschoolNET:

services:
  mysql:
    image: "mysql:5.7"
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - smartschooldb:/var/lib/mysql
    networks:
      - mysqlNET
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_ROOT_HOST=%
      - bind-address:0.0.0.0

  smartschool:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartschool
    networks:
      - mysqlNET
      - smartschoolNET
    ports:
      - 5001:80
    environment:
      - DBHOST=mysql
    depends_on:
      - mysql
